all :
	make -C manager/
	make -C plugin/matsu/
	make -C plugin/take/

install :
	make -C manager/ install 
	make -C plugin/matsu install 
	make -C plugin/take install

clean :
	make -C manager/ clean
	make -C plugin/matsu clean
	make -C plugin/take clean


